version: '3.5'

services:
  portainer-standalone:
    image: portainer-standalone-image
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data:/data
     - /etc/localtime:/etc/localtime
    ports: 
     - 9000:9000
