version: '3'

services:
  portainer:
    image: portainer/portainer:1.12.1
    container_name: portainer
    ports:
     - "7095:9000"
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data:/data
    labels:
     - traefik.frontend.rule=Host:portainer.services.alin.be
     - traefik.backend=portainer
     - traefik.port=9000
     - traefik.frontend.entryPoints=https,http
    networks:
        - web

networks:
  web:
    external:
      name: traefik_webgateway
