version: '3.3'

services:
  portainer:
    image: portainer/portainer:1.15.5
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=9000
        - traefik.frontend.rule=Host:portainer.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data:/data
     - /etc/localtime:/etc/localtime

networks:
  default:
    external:
      name: traefik-net
