FROM registry.services.alin.be/portainer/portainer:v1
COPY localtime /etc/localtime
#RUN apk add --update bash curl
#HEALTHCHECK --interval=10s --timeout=10s --retries=3 CMD curl -f http://localhost:9000/ || exit 1
