# Don't edit this file, user DockerfileTemplate and buildImage.sh
###############################################
FROM registry.services.alin.be/portainer/portainer:1.17.1
COPY localtime /etc/localtime
