# Don't edit this file, user DockerfileTemplate and buildImage.sh
###############################################
FROM registry.services.alin.be/portainer/portainer:1.16.5
COPY localtime /etc/localtime
